version: '3.8'

services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - hls-network

  app:
    image: yauhenivas/home-library-service:part3
    build: .
    restart: always
    environment:
      - PORT=${PORT}
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - ${PORT}:${PORT}
    networks:
      - hls-network

volumes:
  database: {}

networks:
  hls-network:
    driver: bridge